### ISSUE TITLE
Nicht nur eine Seite / URL prüfen, sondern ganze Website (z.B. anhand Sitemap oder Hyperlinks)

### ISSUE THREAD

**Issue by alxndr-w** [eaCe/site_check#1]
Hey @eaCe, wir arbeiten auch irgendwie oft an ähnlichen Dingen / Problemstellungen. :D

Wäre es nicht sinnvoll, nicht nur eine Seite zu prüfen sondern sich durch den ganzen Baum (bspw. anhand einer Sitemap) durchzuarbeiten?

--
Ich liebäugle damit, so etwas wie den site_check in https://github.com/alexplusde/wenns_sein_muss zu integrieren. Und zwar so, dass man beim "absurfen" einer REDAXO-Website prüfen könnte, ob man alle Cookies, Storage und sonstigen Elemente bereits erfasst / verzeichnet hat und so vielleicht auch Änderungen seitens der Dienste mitbekommt.

Wenn du mal Zeit und Lust hast, Mail mir an meine geschäftliche Mail-Adresse.

**Comment by eaCe** [comment]
Hi @alxndr-w ich habe das aus aktuellem Anlass zusammengeschustert ;) 

Man hat mich auch bereits gefragt, ob man nicht einmal die komplette Seite durchsuchen kann. Das wäre natürlich sehr viel Output und würde, je nach Größe, sehr lange dauern. Ich habe ich der Vergangenheit schon zwei Crawler gebaut, bei größeren Seiten sind immer wieder Probleme und Abbrüche aufgetreten. 

Aus einer REDAXO-Installation hast du damit erst mal keine Chance. Man braucht einen Nodejs-Server. Das ganze läuft in diesem Falle mit playwright. Für PHP gibt es chrome-php, allerdings benötigt man auf dem Server bereits einen ausführbaren Chromium. 

Mit meiner Grundlage sehe ich da keine Möglichkeit.

**Comment by eaCe** [comment]
Eventuell wäre das eine Möglichkeit: https://github.com/minkphp/Mink

**Comment by alxndr-w** [comment]
Ah, logisch, das muss ja nicht nur statisch analysiert werden, sondern die Website muss ausgeführt werden.
