### ISSUE TITLE
KB Anzeige bei den gefundenen Dateien

### ISSUE THREAD

**Issue by olien** [eaCe/site_check#2]
Wäre so etwas möglich? ggf. noch eine Sortierung einbauen?

**Comment by eaCe** [comment]
@olien öh sicher, denke ich.. Sortiert wird es bereits. Welche Art von Sortierung meinst du?

**Comment by eaCe** [comment]
Ist beides drin

**Comment by eaCe** [comment]
![grafik](https://user-images.githubusercontent.com/2708231/200003398-54b96b3f-a463-4db2-9c4f-039dec4ac17f.png)
